services:
  docs:
    image: az_ecommerce_local_docs
    container_name: az_ecommerce_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./az_ecommerce:/app/az_ecommerce:z
    ports:
      - '9000:9000'
    command: /start-docs
